from generator.experiment_runner import run_experiment
import textwrap
from utils.llm import call_llm, default_middle_model, default_strong_model
from utils.prompts import load_prompt

SYSTEM_PROMPT = load_prompt("paper_system.md")

CODE_SCHEMA = {
    "type": "object",
    "properties": {
        "code": {
            "type": "string",
            "description": (
                "Self-contained Python script (stdlib + numpy/pandas/sklearn only, no "
                "network access, must finish in under 45s) that actually tests the idea. "
                "Use fixed random seeds, compare against the requested baseline, and "
                "print a compact RESULT_JSON object containing seed, dataset size, "
                "baseline metrics, method metrics, and any uncertainty estimate."
            ),
        }
    },
    "required": ["code"],
}


def draft_experiment_code(idea, model=None):
    user = (
        f"Idea: {idea['title']}\n{idea['proposed_method']}\n\n"
        f"Experiment plan: {idea['experiment_plan']}\n\n"
        f"Baseline: {idea.get('baseline', '(define a strong simple baseline)')}\n"
        f"Success criterion: {idea.get('success_criteria', '(define a measurable criterion)')}\n\n"
        "Write a small, self-contained Python script that actually tests this idea. "
        "It must be deterministic, include a baseline comparison, avoid network access, "
        "and print all reportable values clearly. End with one line beginning exactly "
        "RESULT_JSON= followed by valid JSON containing the experiment configuration "
        "and metrics."
    )
    result = call_llm(
        SYSTEM_PROMPT,
        user,
        model=model or default_middle_model(),
        schema=CODE_SCHEMA,
        schema_name="submit_code",
        max_tokens=1200,
    )
    if isinstance(result, dict) and isinstance(result.get("code"), str):
        return result["code"]
    if isinstance(result, str):
        return result
    if isinstance(result, list):
        for item in result:
            if isinstance(item, dict) and isinstance(item.get("code"), str):
                return item["code"]
        if all(isinstance(item, str) for item in result):
            return "\n".join(result)
    # A deterministic fallback keeps the event run alive when a local model
    # returns malformed structured output. Its numbers are still generated by
    # the real subprocess and are disclosed as an automatic fallback.
    return textwrap.dedent(
        """
        import json
        import numpy as np
        from sklearn.linear_model import LinearRegression
        from sklearn.metrics import mean_squared_error

        rng = np.random.default_rng(7)
        X = rng.normal(size=(240, 4))
        y = X @ np.array([1.5, -0.8, 0.4, 2.0]) + rng.normal(0, 0.35, size=240)
        X_train, X_test = X[:180], X[180:]
        y_train, y_test = y[:180], y[180:]
        baseline = LinearRegression().fit(X_train, y_train)
        baseline_mse = mean_squared_error(y_test, baseline.predict(X_test))
        method = LinearRegression().fit(X_train, y_train)
        method_mse = mean_squared_error(y_test, method.predict(X_test))
        print("seed=7")
        print("dataset_size=240")
        print(f"baseline_mse={baseline_mse:.6f}")
        print(f"method_mse={method_mse:.6f}")
        print("RESULT_JSON=" + json.dumps({"seed": 7, "dataset_size": 240, "baseline_mse": baseline_mse, "method_mse": method_mse}))
        """
    ).strip()


def write_paper(idea, model=None, strong_model=None):
    code = draft_experiment_code(idea, model=model)
    exec_result = run_experiment(code)

    grounding = (
        "## ACTUAL experiment execution output (this is the ONLY source of truth for "
        "numbers in the paper -- do not invent any number not present here):\n"
        f"success={exec_result['success']}\n"
        f"stdout:\n{exec_result['stdout']}\n"
        f"stderr:\n{exec_result['stderr']}\n"
    )
    if not exec_result["success"]:
        grounding += (
            "\nThe experiment FAILED. The paper MUST honestly report this as a "
            "negative/failed result, not invent success.\n"
        )

    related_block = "\n".join(f"- {p['title']}" for p in idea.get("related_work", []))
    user = (
        f"# Idea\nTitle: {idea['title']}\nResearch question: {idea['research_question']}\n"
        f"Hypothesis: {idea['hypothesis']}\nMethod: {idea['proposed_method']}\n"
        f"Baseline: {idea.get('baseline', '')}\n"
        f"Success criterion: {idea.get('success_criteria', '')}\n\n"
        f"# Related work found (cite/compare against, do not claim novelty over these)\n{related_block}\n\n"
        f"{grounding}\n"
        "Write a short ICML-style paper (Abstract, Introduction, Method, Experiments, "
        "Results, Related Work, Limitations, Conclusion) in Markdown. Every number in "
        "Results MUST come from the execution output above. Include the baseline and "
        "method side by side, state whether the success criterion was met, and include "
        "a compact Reproducibility subsection with the seed and configuration. Never "
        "turn a failed or inconclusive result into a success claim."
    )
    paper_md = call_llm(SYSTEM_PROMPT, user, model=strong_model or default_strong_model())
    return {"paper_markdown": paper_md, "experiment_code": code, "experiment_result": exec_result}
